ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CREATE_LIVREUR';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_LIVREUR';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DELETE_LIVREUR';
